# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=datetime.datetime(2017, 5, 16, 13, 14, 34, 131367, tzinfo=utc))),
                ('end_time', models.TimeField(default=datetime.datetime(2017, 5, 16, 13, 14, 34, 131425, tzinfo=utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.TimeField(default=datetime.datetime(2017, 5, 16, 13, 14, 34, 117667, tzinfo=utc))),
                ('end_time', models.TimeField(default=datetime.datetime(2017, 5, 16, 13, 14, 34, 129480, tzinfo=utc))),
                ('resource_logo', models.CharField(blank=True, max_length=1000)),
                ('resource_description', models.CharField(blank=True, max_length=1000)),
                ('resource_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='tag',
            field=models.ManyToManyField(blank=True, to='reserve.Tag'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.Resource'),
        ),
    ]
